'use strict';
const $ = id => document.getElementById(id);
const palette = ['#b494f5','#ec9cc5','#79cabd','#e6b572','#87ade7','#da8c9f'];
let board = {version:1,title:'Mi multiverso',streets:Array.from({length:20},(_,i)=>({name:`Calle ${i+1}`,series:'',color:palette[Math.floor(i/4)%6],price:100+i*20,rent:10+i*2,image:null,zoom:1,x:.5,y:.5}))};
let selected=0,dirty=false,db,drag,noticeTimer;const images=new Map();let revision=0;
const current=()=>board.streets[selected];
function notify(message){$('status').textContent=message;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('status').textContent='',4500)}
function changed(){dirty=true;revision++;$('save').textContent='Guardar cambios •'}
function imageFor(src){if(!src)return null;return images.get(src)}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('La imagen no se pudo leer.'));im.src=src})}
function draw(canvas,street){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const im=imageFor(street.image);if(!im)return;const scale=Math.max(canvas.width/im.width,canvas.height/im.height)*street.zoom;const w=im.width*scale,h=im.height*scale;ctx.drawImage(im,-(w-canvas.width)*street.x,-(h-canvas.height)*street.y,w,h)}
function coords(i){if(i<7)return [1,i+1];if(i<13)return [i-5,7];if(i<19)return [7,19-i];return [25-i,1]}
function renderBoard(){document.querySelectorAll('.tile').forEach(x=>x.remove());let street=0;for(let i=0;i<24;i++){const [row,col]=coords(i);const el=document.createElement('button');el.className='tile';el.style.gridArea=`${row}/${col}`;if(i%6===0){el.classList.add('special');const symbols=['↗','✦','☾','↔'],names=['SALIDA','SORPRESA','DESCANSO','INTERCAMBIO'];el.innerHTML=`<b>${symbols[i/6]}</b>${names[i/6]}`;el.title='Casilla especial: disponible en la etapa de reglas';el.onclick=()=>notify('Esta casilla especial se configurará con las reglas del juego.')}else{const idx=street++,s=board.streets[idx];el.dataset.street=idx;el.classList.toggle('selected',idx===selected);el.setAttribute('aria-label',`Editar ${s.name}`);el.setAttribute('aria-pressed',String(idx===selected));const stripe=document.createElement('div');stripe.className='stripe';stripe.style.background=s.color;const canvas=document.createElement('canvas');canvas.className='art';canvas.width=160;canvas.height=120;const title=document.createElement('span');title.className='title';title.textContent=s.name;const cost=document.createElement('span');cost.className='cost';cost.textContent=`$${s.price}`;el.append(stripe,canvas,title,cost);draw(canvas,s);el.onclick=()=>{selected=idx;sync();renderBoard()}}$('board').append(el)}$('count').textContent=`${board.streets.filter(s=>s.image).length} / 20 imágenes`;document.querySelector('.center h2').textContent=board.title}
function redraw(){draw($('preview'),current());const canvas=document.querySelector(`[data-street="${selected}"] canvas`);if(canvas)draw(canvas,current());$('zoom-value').value=`${current().zoom.toFixed(1)}×`;for(const [id,key] of [['zoom','zoom'],['pan-x','x'],['pan-y','y']])$(id).value=current()[key];$('crop-hint').style.display=current().image?'none':'flex'}
function sync(){const s=current();$('selected-label').textContent=`Calle ${selected+1}`;for(const key of ['name','series','color','price','rent'])$(key).value=s[key];$('board-title').value=board.title;redraw()}
for(const key of ['name','series','color','price','rent'])$(key).addEventListener('input',()=>{if(['price','rent'].includes(key)){if(!$(key).validity.valid||$(key).value==='')return;current()[key]=Number($(key).value)}else current()[key]=$(key).value;changed();renderBoard()});
$('board-title').oninput=()=>{board.title=$('board-title').value;changed();document.querySelector('.center h2').textContent=board.title};
for(const [id,key] of [['zoom','zoom'],['pan-x','x'],['pan-y','y']])$(id).oninput=()=>{current()[key]=Number($(id).value);changed();redraw()};
$('reset').onclick=()=>{Object.assign(current(),{zoom:1,x:.5,y:.5});changed();redraw()};
$('remove').onclick=()=>{Object.assign(current(),{image:null,zoom:1,x:.5,y:.5});changed();renderBoard();redraw()};
$('image').onchange=async()=>{const file=$('image').files[0],target=current();$('image').value='';if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024){notify('Elige un PNG, JPG o WebP de hasta 8 MB.');return}const url=URL.createObjectURL(file);try{const im=await loadImage(url);if(im.width*im.height>40000000)throw new Error('Usa una imagen de hasta 40 megapíxeles.');const scale=Math.min(1,1400/Math.max(im.width,im.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(im.width*scale));canvas.height=Math.max(1,Math.round(im.height*scale));canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);const src=canvas.toDataURL('image/webp',.88);images.set(src,await loadImage(src));Object.assign(target,{image:src,zoom:1,x:.5,y:.5});changed();renderBoard();redraw();notify('Imagen lista. Arrastra para elegir el encuadre.')}catch(e){notify(e.message)}finally{URL.revokeObjectURL(url)}};
function pan(dx,dy){const s=current(),im=imageFor(s.image);if(!im)return;const rect=$('crop').getBoundingClientRect(),scale=Math.max(rect.width/im.width,rect.height/im.height)*s.zoom,overflowX=im.width*scale-rect.width,overflowY=im.height*scale-rect.height;if(overflowX>0.01)s.x=Math.max(0,Math.min(1,s.x-dx/overflowX));if(overflowY>0.01)s.y=Math.max(0,Math.min(1,s.y-dy/overflowY));changed();redraw()}
$('crop').onpointerdown=e=>{if(!current().image)return;drag={x:e.clientX,y:e.clientY};$('crop').setPointerCapture(e.pointerId)};$('crop').onpointermove=e=>{if(!drag)return;pan(e.clientX-drag.x,e.clientY-drag.y);drag={x:e.clientX,y:e.clientY}};for(const type of ['pointerup','pointercancel','lostpointercapture'])$('crop').addEventListener(type,()=>drag=null);
$('crop').onkeydown=e=>{const keys={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]};if(keys[e.key]){e.preventDefault();pan(...keys[e.key])}};
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('kaoru-studio',1);req.onupgradeneeded=()=>req.result.createObjectStore('boards');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function readSaved(){return new Promise((resolve,reject)=>{const req=db.transaction('boards').objectStore('boards').get('draft');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function hydrate(value){validate(value);const entries=await Promise.all(value.streets.filter(s=>s.image).map(async s=>[s.image,await loadImage(s.image)]));for(const [src,im]of entries)images.set(src,im);board=value;selected=0;sync();renderBoard()}
function validate(b){if(!b||b.version!==1||typeof b.title!=='string'||b.title.length>60||!Array.isArray(b.streets)||b.streets.length!==20)throw new Error('El archivo no es un tablero Kaoru v1 válido.');for(const s of b.streets){if(!s||!['name','series'].every(k=>typeof s[k]==='string'&&s[k].length<=40)||!/^#[a-f\d]{6}$/i.test(s.color)||!['price','rent'].every(k=>Number.isInteger(s[k])&&s[k]>=0&&s[k]<=100000)||!Number.isFinite(s.zoom)||s.zoom<1||s.zoom>4||![s.x,s.y].every(n=>Number.isFinite(n)&&n>=0&&n<=1)||!(s.image===null||(typeof s.image==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s.image)&&s.image.length<12000000)))throw new Error('El tablero contiene datos de calle inválidos.')}}
$('save').onclick=async()=>{try{validate(board);if(!db)db=await openDB();const savedRevision=revision;await new Promise((resolve,reject)=>{const tx=db.transaction('boards','readwrite');tx.objectStore('boards').put(structuredClone(board),'draft');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});if(savedRevision===revision){dirty=false;$('save').textContent='Guardar cambios'}notify('Guardado en este navegador. Exporta para tener una copia.')}catch(e){notify('No se pudo guardar. Exporta el tablero para conservarlo.')}};
$('export').onclick=()=>{try{validate(board);const blob=new Blob([JSON.stringify(board,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='kaoru-tablero.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Tablero exportado con sus imágenes y encuadres.')}catch(e){notify(e.message)}};
$('import').onclick=()=>$('json').click();$('json').onchange=async()=>{const file=$('json').files[0];$('json').value='';if(!file)return;if(file.size>50000000)return notify('El archivo supera los 50 MB.');if(dirty&&!confirm('Importar reemplazará tus cambios sin guardar. ¿Continuar?'))return;try{const value=JSON.parse(await file.text());await hydrate(value);changed();notify('Tablero importado. Guarda los cambios para conservarlo.')}catch(e){notify('No se pudo importar: '+e.message)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
(async()=>{sync();renderBoard();try{db=await openDB();const saved=await readSaved();if(saved&&!dirty)await hydrate(saved)}catch(e){notify('El guardado local no está disponible. Puedes exportar tu tablero.')}})();
