'use strict';
const {randomInt}=require('node:crypto');
const Model=require('./public/editor/board-model.js');
const cards=require('./cards.cjs');
const tiles=Model.tiles();
const START_CASH=1000,GO_SALARY=150,JAIL_FINE=150,RENT_MULTIPLIER=2;
const fail=m=>{throw new Error(m)};
function log(g,text){g.log.push(text);g.log=g.log.slice(-70)}
function player(g,id){return g.players.find(p=>p.id===id)||fail('No perteneces a esta partida.')}
function asset(board,pos){const t=tiles[pos];if(!t)return null;if(t.type==='street')return {...board.streets[t.street],type:'street',position:pos};if(t.type==='transport')return {type:t.type,name:t.name,price:200,position:pos};if(t.type==='utility')return {type:t.type,name:t.name,price:150,position:pos};return null}
function groupPositions(board,groupId){return tiles.filter(t=>t.type==='street'&&board.streets[t.street].groupId===groupId).map(t=>t.position)}
function netWorth(g,board,p){let n=p.cash;for(const [pos,o]of Object.entries(g.owners)){if(o.id!==p.id)continue;const a=asset(board,+pos);n+=o.mortgaged?Math.floor(a.price/2):a.price;if(o.level)n+=o.level*a.buildCost}return n-g.debts.filter(d=>d.from===p.id).reduce((a,d)=>a+d.amount,0)}
function create(ids,settings={}){return {players:ids.map(id=>({id,cash:START_CASH,pos:0,jail:0,pass:0,discount:0,out:false})),owners:{},turn:0,round:1,maxRounds:settings.rounds===0?0:Math.min(100,Math.max(5,Number(settings.rounds)||30)),potEnabled:!!settings.pot,pot:0,phase:'roll',dice:[1],extra:false,doubles:0,debts:[],decks:{chance:[],community:[]},log:[`La partida comenzó. Todas reciben ${START_CASH}.`],event:null,sequence:0,winners:[]}}
function charge(g,from,to,amount){if(amount>0)g.debts.push({from,to,amount:Math.floor(amount)})}
function settle(g){for(const d of g.debts){const p=player(g,d.from);const paid=Math.min(Math.max(0,p.cash),d.amount);p.cash-=paid;d.amount-=paid;if(d.to==='pot')g.pot+=paid;else if(d.to!=='bank')player(g,d.to).cash+=paid}g.debts=g.debts.filter(d=>d.amount>0&&!player(g,d.from).out);if(g.debts.length){if(g.phase!=='debt')g.resume=g.phase;g.phase='debt'}else if(g.phase==='debt'){g.phase=g.resume||'end';delete g.resume}}
function jail(g,p){p.pos=10;p.jail=3;g.extra=false;g.doubles=0;log(g,'Una jugadora fue enviada a prisión.');g.event={kind:'jail',player:p.id}}
function move(g,p,steps,salary=true){const from=p.pos;let next=from+steps;if(salary&&steps>0&&next>=40){p.cash+=GO_SALARY;log(g,`Se cobraron ${GO_SALARY} al pasar GO.`)}p.pos=((next%40)+40)%40;g.sequence++;g.movement={id:g.sequence,player:p.id,from,to:p.pos,steps};}
function complete(g,board,id,groupId){return groupPositions(board,groupId).every(pos=>g.owners[pos]?.id===id&&!g.owners[pos].mortgaged)}
function rent(g,board,pos,dice){const a=asset(board,pos),o=g.owners[pos];if(!o||o.mortgaged)return 0;if(a.type==='street'){const base=o.level?a.upgradeRents[o.level-1]:(complete(g,board,o.id,a.groupId)?a.groupRent:a.rent);return Math.floor(base*RENT_MULTIPLIER)}const count=Object.entries(g.owners).filter(([key,v])=>v.id===o.id&&asset(board,+key).type===a.type).length;return a.type==='transport'?[50,100,200,400][count-1]:dice*(count===2?40:16)}
function shuffled(n,rng){const a=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=rng(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function cardVisual(board,type,index){const item=board&&board.cards&&Array.isArray(board.cards[type])?board.cards[type][index]:null;if(!item||typeof item!=='object')return {};return {text:typeof item.text==='string'&&item.text.trim()?item.text:undefined,image:typeof item.image==='string'&&item.image.startsWith('data:image/')?item.image:null}}
function land(g,board,p,rng,depth=0){if(depth>8)fail('Demasiados movimientos encadenados.');const t=tiles[p.pos],a=asset(board,p.pos);if(a){const o=g.owners[p.pos];if(!o){g.phase='buy';g.pending=p.pos;return}if(o.id!==p.id){let amount=rent(g,board,p.pos,g.dice.reduce((sum,n)=>sum+n,0));if(amount&&p.discount){amount=Math.max(0,amount-100);p.discount--;log(g,'El cupón redujo el alquiler en hasta 100.')}charge(g,p.id,o.id,amount);log(g,`Alquiler: ${amount} por ${a.name}.`)}return}
if(t.type==='goToJail'){jail(g,p);return}if(t.type==='parking'&&g.potEnabled){log(g,`Se cobró el bote de ${g.pot}.`);p.cash+=g.pot;g.pot=0;return}if(t.type==='tax'){const amount=p.pos===4?300:200;charge(g,p.id,g.potEnabled?'pot':'bank',amount);log(g,`Impuesto: ${amount}.`);return}
if(['chance','community'].includes(t.type)){const deck=g.decks[t.type];if(!deck.length)deck.push(...shuffled(cards[t.type].length,rng));const index=deck.shift();const baseCard=cards[t.type][index];const visual=cardVisual(board,t.type,index);const card={...baseCard,...visual,text:visual.text||baseCard.text};g.event={kind:'card',text:card.text,image:card.image||null,player:p.id,deck:t.type};log(g,card.text);switch(card.effect){case'receive':p.cash+=card.amount;break;case'pay':charge(g,p.id,'bank',card.amount);break;case'fine':charge(g,p.id,g.potEnabled?'pot':'bank',card.amount);break;case'jail':jail(g,p);g.event={kind:'card',text:card.text,player:p.id};break;case'pass':p.pass++;break;case'discount':p.discount++;break;case'birthday':for(const q of g.players)if(!q.out&&q.id!==p.id)charge(g,q.id,p.id,card.amount);break;case'everyone':for(const q of g.players)if(!q.out&&q.id!==p.id)charge(g,p.id,q.id,card.amount);break;case'repairs':{let amount=0;for(const o of Object.values(g.owners))if(o.id===p.id)amount+=o.level===5?200:o.level*50;charge(g,p.id,'bank',amount);break}default:{let steps=0;if(card.effect==='go')steps=40-p.pos;else if(card.effect==='back')steps=-card.amount;else if(card.effect==='forward')steps=card.amount;else if(card.effect==='station'){steps=1;while(tiles[(p.pos+steps)%40].type!=='transport')steps++}else if(card.effect==='backStation'){steps=-1;while(tiles[(p.pos+steps+40)%40].type!=='transport')steps--}move(g,p,steps,steps>0);land(g,board,p,rng,depth+1)}}}}
function resolveAuction(g,board){const a=g.auction;if(!a)return;if(a.bidder){player(g,a.bidder).cash-=a.bid;g.owners[a.pos]={id:a.bidder,level:0,mortgaged:false};log(g,`Subasta adjudicada por ${a.bid}.`)}else log(g,'Subasta sin ofertas. La propiedad sigue libre.');delete g.auction;g.phase='end';next(g,board)}
function checkEnd(g,board){const active=g.players.filter(p=>!p.out);if(active.length<=1){g.phase='finished';g.winners=active.map(p=>p.id);return}if(g.maxRounds&&g.round>g.maxRounds){const max=Math.max(...active.map(p=>netWorth(g,board,p)));g.winners=active.filter(p=>netWorth(g,board,p)===max).map(p=>p.id);g.phase='finished'}}
function next(g,board){g.extra=false;g.doubles=0;do{g.turn++;if(g.turn===g.players.length){g.turn=0;g.round++}}while(g.players[g.turn].out);g.phase='roll';checkEnd(g,board)}
function finishTurn(g,board){if(g.phase==='end')next(g,board)}
function canTransfer(g,board,pos,id){const o=g.owners[pos],a=asset(board,pos);return o&&o.id===id&&!o.mortgaged&&(a.type!=='street'||groupPositions(board,a.groupId).every(p=>!g.owners[p]?.level))}
function act(g,board,id,action,rng=n=>randomInt(n),now=Date.now()){const p=player(g,id);if(g.phase==='finished'||p.out)fail('Ya no puedes actuar.');const turn=g.players[g.turn].id===id,type=action.type;g.event=null;
if(type==='resign'){p.out=true;for(const [pos,o]of Object.entries(g.owners))if(o.id===id)delete g.owners[pos];g.debts=g.debts.filter(d=>d.from!==id);for(const d of g.debts)if(d.to===id)d.to='bank';p.cash=0;log(g,'Una jugadora abandonó. Sus propiedades vuelven al banco.');if(g.auction){if(g.auction.bidder===id){g.auction.bid=0;g.auction.bidder=null}g.auction.passed.push(id)}if(g.trade){delete g.trade;g.phase='end'}settle(g);checkEnd(g,board);if(turn&&g.phase!=='finished'){delete g.auction;g.extra=false;if(g.phase==='debt')g.resume='end';else next(g,board)}return}
if(g.phase==='auction'){if(!['bid','passAuction'].includes(type))fail('La subasta está en curso.');const a=g.auction;if(now>=a.until){resolveAuction(g,board);return}if(type==='bid'){const bid=Number(action.amount);if(a.passed.includes(id)||!Number.isInteger(bid)||bid<a.bid+10||bid>p.cash)fail('Oferta inválida: mínimo 10 más y saldo suficiente.');a.bid=bid;a.bidder=id;a.until=now+30000}else{if(a.bidder===id)fail('Tu oferta sigue siendo la mayor.');if(!a.passed.includes(id))a.passed.push(id)}if(g.players.filter(q=>!q.out&&q.id!==a.bidder).every(q=>a.passed.includes(q.id)))resolveAuction(g,board);return}
if(g.phase==='trade'){const t=g.trade;if(type==='cancelTrade'&&[t.from,t.to].includes(id)){delete g.trade;g.phase=t.resume;return}if(type!=='acceptTrade'||id!==t.to)fail('Espera la respuesta al intercambio.');if(!canTransfer(g,board,t.give,t.from)||!canTransfer(g,board,t.receive,t.to))fail('Las propiedades ya no están disponibles.');g.owners[t.give].id=t.to;g.owners[t.receive].id=t.from;delete g.trade;g.phase=t.resume;log(g,'Intercambio aceptado.');return}
const owes=g.debts.some(d=>d.from===id);if(g.phase==='debt'&&!owes)fail('Otra jugadora está resolviendo una deuda.');if(!turn&&!owes)fail('No es tu turno.');
if(['build','sellBuilding','mortgage','unmortgage'].includes(type)){if(!['roll','end','debt'].includes(g.phase))fail('Resuelve primero la casilla.');const pos=Number(action.position),a=asset(board,pos),o=g.owners[pos];if(!a||o?.id!==id)fail('No es tu propiedad.');if(type==='build'){if(owes||a.type!=='street'||!complete(g,board,id,a.groupId)||o.level>=5||p.cash<a.buildCost)fail('Necesitas grupo completo libre de hipotecas y dinero.');const levels=groupPositions(board,a.groupId).map(pos=>g.owners[pos].level);if(o.level>Math.min(...levels))fail('Construye de forma equilibrada.');o.level++;p.cash-=a.buildCost;log(g,`Mejora construida en ${a.name}.`)}else if(type==='sellBuilding'){if(!o.level)fail('No hay edificios.');const max=Math.max(...groupPositions(board,a.groupId).map(pos=>g.owners[pos]?.level||0));if(o.level<max)fail('Vende los edificios de forma equilibrada.');o.level--;p.cash+=Math.floor(a.buildCost/2)}else if(type==='mortgage'){if(o.mortgaged||(a.type==='street'&&groupPositions(board,a.groupId).some(pos=>g.owners[pos]?.level)))fail('Vende antes todos los edificios del grupo.');o.mortgaged=true;p.cash+=Math.floor(a.price/2)}else{const cost=Math.ceil(Math.floor(a.price/2)*1.1);if(owes||!o.mortgaged||p.cash<cost)fail('Saldo insuficiente o propiedad no hipotecada.');p.cash-=cost;o.mortgaged=false}settle(g);if(g.players[g.turn].out&&g.phase!=='debt'){checkEnd(g,board);if(g.phase!=='finished'){g.extra=false;next(g,board)}}return}
if(type==='bankrupt'){if(!owes)fail('No tienes deuda pendiente.');const available=Object.entries(g.owners).some(([pos,o])=>o.id===id&&(o.level>0||!o.mortgaged));if(available)fail('Vende mejoras e hipoteca antes de declararte en bancarrota.');p.out=true;p.cash=0;for(const [pos,o]of Object.entries(g.owners))if(o.id===id)delete g.owners[pos];g.debts=g.debts.filter(d=>d.from!==id);for(const d of g.debts)if(d.to===id)d.to='bank';settle(g);checkEnd(g,board);if(turn&&g.phase!=='finished'){g.extra=false;if(g.phase==='debt')g.resume='end';else next(g,board)}log(g,'Bancarrota. Las propiedades vuelven al banco.');return}
if(g.phase==='debt')fail('Primero resuelve la deuda.');
if(type==='offerTrade'){if(!['roll','end'].includes(g.phase))fail('No puedes negociar ahora.');const to=player(g,action.to),give=Number(action.give),receive=Number(action.receive);if(to.out||to.id===id||!canTransfer(g,board,give,id)||!canTransfer(g,board,receive,to.id))fail('Solo se intercambian propiedades sin hipotecas ni edificios en su grupo.');g.trade={from:id,to:to.id,give,receive,resume:g.phase};g.phase='trade';return}
if(type==='release'){if(g.phase!=='roll'||!p.jail)fail('No estás en prisión.');if(action.method==='card'){if(!p.pass)fail('No tienes carta.');p.pass--}else{if(p.cash<JAIL_FINE)fail(`Necesitas ${JAIL_FINE}.`);p.cash-=JAIL_FINE;log(g,`Pagó ${JAIL_FINE} para salir de prisión.`)}p.jail=0;return}
if(type==='roll'){if(g.phase!=='roll')fail('No puedes tirar ahora.');g.dice=[rng(6)+1];const die=g.dice[0];g.phase='end';g.extra=false;g.doubles=0;if(p.jail){if(die===6){p.jail=0;log(g,'Sacó 6 y salió de prisión.')}else{p.jail--;if(p.jail){log(g,`No sacó 6. Sigue en prisión (${p.jail} intento${p.jail===1?'':'s'}).`);finishTurn(g,board);return}charge(g,id,'bank',JAIL_FINE);log(g,`Tercer intento fallido: paga ${JAIL_FINE} y sale de prisión.`)}}move(g,p,die);land(g,board,p,rng);settle(g);finishTurn(g,board);return}
if(type==='buy'){if(g.phase!=='buy')fail('No hay compra pendiente.');const a=asset(board,g.pending);if(p.cash<a.price)fail('Saldo insuficiente. Puedes pasar.');p.cash-=a.price;g.owners[g.pending]={id,level:0,mortgaged:false};log(g,`Compra: ${a.name} por ${a.price}.`);delete g.pending;g.phase='end';finishTurn(g,board);return}
if(type==='passBuy'){if(g.phase!=='buy')fail('No hay compra pendiente.');const a=asset(board,g.pending);log(g,`Pasó ${a.name}. La propiedad sigue libre.`);delete g.pending;g.phase='end';finishTurn(g,board);return}
if(type==='auction')fail('Las propiedades libres ya no se subastan: compra o pasa.')
if(type==='end'){if(g.phase!=='end')fail('Tienes una acción pendiente.');next(g,board);return}fail('Acción desconocida.');}
module.exports={create,act,asset,rent,netWorth,resolveAuction};
