'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const {randomBytes,randomInt,createHash,scryptSync,timingSafeEqual}=require('node:crypto');
const Game=require('./game.cjs'),Model=require('./public/editor/board-model.js');
const ROOT=__dirname;
async function main(){
const db=await require('./store.cjs').openStore();
const PUBLIC_URL=process.env.PUBLIC_URL||process.env.RENDER_EXTERNAL_URL||'';
const streams=new Map(),chatStreams=new Map(),rate=new Map();const uid=()=>randomBytes(16).toString('hex');
const hash=s=>createHash('sha256').update(s).digest('hex');
const error=(message,status=400)=>{const e=new Error(message);e.status=status;throw e};
const defaultBoard=JSON.parse(fs.readFileSync(path.join(ROOT,'default-board.json'),'utf8'));Model.validate(defaultBoard);
const BOARD_EFFECTS=new Set(['none','receive','pay','fine','jail','pass','discount','birthday','everyone','repairs','go','back','forward','station','backStation']);
function boardImage(v){return v===null||v===undefined||(typeof v==='string'&&v.length<12000000&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v))}
function validateBoardExtras(board){
 const crop=item=>item&&Number.isFinite(Number(item.zoom))&&Number(item.zoom)>=1&&Number(item.zoom)<=4&&[item.x,item.y].every(n=>Number.isFinite(Number(n))&&Number(n)>=0&&Number(n)<=1)&&boardImage(item.image);
 if(board.cards!==undefined){for(const kind of ['chance','community']){const deck=board.cards?.[kind];if(!Array.isArray(deck)||deck.length<1||deck.length>40)error('Cada mazo debe tener entre 1 y 40 cartas.');for(const card of deck){if(!crop(card)||typeof card.title!=='string'||card.title.length>80||typeof card.text!=='string'||card.text.length>420||!BOARD_EFFECTS.has(card.effect)||!Number.isInteger(Number(card.amount))||Number(card.amount)<0||Number(card.amount)>1000000)error('Hay una cartilla inválida en el tablero.')}}}
 if(board.specialCards!==undefined){for(const [pos,card] of Object.entries(board.specialCards)){if(!['0','4','10','20','30','38'].includes(pos)||!crop(card)||typeof card.text!=='string'||card.text.length>420)error('Hay una cartilla especial inválida.')}}
 return board;
}
function checkedBoard(value){const board=Model.migrate(structuredClone(value));Model.validate(board);validateBoardExtras(board);return board}
async function savedBoard(userId){const row=await db.prepare('SELECT board FROM board_configs WHERE user_id=?').get(userId);if(!row)return null;try{return checkedBoard(JSON.parse(row.board))}catch{return null}}
const getUser=async id=>(await db.prepare('SELECT * FROM users WHERE id=?').get(id));
function normalizeHex(value,fallback){let s=String(value||'').trim().toLowerCase();if(/^[0-9a-f]{3}$/.test(s))s='#'+s;if(/^#[0-9a-f]{3}$/.test(s))s='#'+[...s.slice(1)].map(x=>x+x).join('');if(/^[0-9a-f]{6}$/.test(s))s='#'+s;return /^#[0-9a-f]{6}$/.test(s)?s:fallback}
function chatStyle(value={}){const align=['left','center','right'].includes(value?.textAlign)?value.textAlign:'left';return {mode:value?.mode==='solid'?'solid':'gradient',bubble1:normalizeHex(value?.bubble1,'#dba9f6'),bubble2:normalizeHex(value?.bubble2,'#f5a9d4'),text:normalizeHex(value?.text,'#2e1736'),angle:Math.round(Math.max(0,Math.min(360,Number(value?.angle)||135))),fontSize:Math.round(Math.max(11,Math.min(24,Number(value?.fontSize)||14))),textAlign:align,textX:Math.round(Math.max(-10,Math.min(10,Number(value?.textX)||0))),textY:Math.round(Math.max(-10,Math.min(10,Number(value?.textY)||0)))}}
function chatFontMeta(p,id){const f=p?.chatFont;if(!f||!f.version||!f.name)return null;return {name:String(f.name).slice(0,90),version:Number(f.version),url:`/api/users/${id}/chat-font?v=${Number(f.version)}`}}
function profile(u){const p=JSON.parse(u.profile);return {id:u.id,username:u.username,name:p.name,version:p.version,adjust:p.adjust,chatStyle:chatStyle(p.chatStyle),chatFont:chatFontMeta(p,u.id),assetIds:p.assetIds||{},assets:Object.fromEntries(['avatar','frame','token'].map(k=>[k,p.assetIds?.[k]?`/api/users/${u.id}/assets/${k}?v=${p.version}`:null]))}}
const boards=new Map();
const MUSIC_TRACK_COUNT=10;
function musicOrder(){const values=Array.from({length:MUSIC_TRACK_COUNT},(_,i)=>i);for(let i=values.length-1;i>0;i--){const j=randomInt(i+1);[values[i],values[j]]=[values[j],values[i]]}return values}
function validMusicSettings(settings){return Array.isArray(settings?.musicOrder)&&settings.musicOrder.length===MUSIC_TRACK_COUNT&&new Set(settings.musicOrder).size===MUSIC_TRACK_COUNT&&settings.musicOrder.every(n=>Number.isInteger(n)&&n>=0&&n<MUSIC_TRACK_COUNT)&&Number.isFinite(Number(settings.musicEpoch))&&Number(settings.musicEpoch)>0}
async function room(code){const row=await db.prepare('SELECT code,host,members,settings,state,revision FROM rooms WHERE code=?').get(code);if(!row)error('No existe esa sala.',404);let settings=JSON.parse(row.settings);if(!validMusicSettings(settings)){settings={...settings,musicOrder:musicOrder(),musicEpoch:Date.now()};await db.prepare('UPDATE rooms SET settings=? WHERE code=?').run(JSON.stringify(settings),code)}let board=boards.get(code);if(!board){const data=await db.prepare('SELECT board FROM rooms WHERE code=?').get(code);board=JSON.parse(data.board);if(boards.size>=8)boards.delete(boards.keys().next().value);boards.set(code,board)}return {...row,board,members:JSON.parse(row.members),settings,state:JSON.parse(row.state)}}
function member(r,u){if(!r.members.some(m=>m.id===u.id))error('No perteneces a esta sala.',403)}
async function snapshot(r){let state=r.state?structuredClone(r.state):null;if(state){delete state.decks;state.players=state.players.map(p=>({...p,netWorth:Game.netWorth(r.state,r.board,p)}))}return {code:r.code,host:r.host,revision:r.revision,serverNow:Date.now(),settings:r.settings,members:await Promise.all(r.members.map(async m=>({...m,...profile(await getUser(m.id))}))),state}}
async function save(r){r.revision++;(await db.prepare('UPDATE rooms SET members=?,state=?,revision=? WHERE code=?').run(JSON.stringify(r.members),JSON.stringify(r.state),r.revision,r.code))}
async function broadcast(r,snap=null){const value=snap||await snapshot(r),data=`id: ${r.revision}\ndata: ${JSON.stringify(value)}\n\n`;for(const client of streams.get(r.code)||[])client.write(data)}
function send(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
async function body(req,limit=70000000){if(Object.hasOwn(req,'payload')){if(req.payloadBytes>limit)error('El archivo es demasiado grande.',413);return req.payload}let size=0,parts=[];for await(const part of req){size+=part.length;if(size>limit)error('El archivo es demasiado grande.',413);parts.push(part)}req.payloadBytes=size;try{return JSON.parse(Buffer.concat(parts).toString()||'{}')}catch{error('JSON inválido.')}}
async function auth(req){const token=(req.headers.cookie||'').match(/(?:^|;\s*)kaoru=([a-f0-9]{64})(?:;|$)/)?.[1];if(!token)error('Inicia sesión.',401);const s=(await db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').get(hash(token),Date.now()));if(!s)error('La sesión expiró.',401);return await getUser(s.user_id)}
function cookie(req,res,token,maxAge=604800){res.setHeader('Set-Cookie',`kaoru=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${PUBLIC_URL.startsWith('https://')?'; Secure':''}`)}
function throttle(req){const ip=req.socket.remoteAddress;const t=rate.get(ip)||{n:0,start:Date.now()};if(Date.now()-t.start>60000){t.n=0;t.start=Date.now()}t.n++;rate.set(ip,t);if(t.n>30)error('Espera un minuto antes de volver a intentar.',429)}
function image(value,kind){if(value===null)return null;if(typeof value!=='string'||value.length>2100000)error('Cada imagen debe ocupar menos de 1.5 MB.');const m=value.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/);if(!m||(['frame','token'].includes(kind)&&m[1]!=='png'))error('Marco y ficha deben ser PNG.');const b=Buffer.from(m[2],'base64');const valid=m[1]==='png'?b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):m[1]==='jpeg'?b[0]===255&&b[1]===216:b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP';if(!valid)error('Imagen inválida.');if(m[1]==='png'&&(b.length<24||b.readUInt32BE(16)>4096||b.readUInt32BE(20)>4096))error('El PNG no debe superar 4096 píxeles por lado.');return value}

function safeFontName(name='Fuente personalizada'){return path.basename(String(name||'Fuente personalizada')).replace(/[^\p{L}\p{N} _().\-]+/gu,'').slice(0,90)||'Fuente personalizada'}
function validFontBytes(buf){if(!Buffer.isBuffer(buf)||buf.length<256||buf.length>2200000)error('La fuente debe ocupar entre 256 bytes y 2 MB.');const tag=buf.subarray(0,4).toString('ascii'),ttf=buf[0]===0&&buf[1]===1&&buf[2]===0&&buf[3]===0;if(!ttf&&!['OTTO','true','typ1'].includes(tag))error('El archivo no parece una fuente TTF/OTF válida.');return true}
function extractFontFromZip(buf){if(buf.length>2600000)error('El ZIP no puede superar 2.5 MB.');let eocd=-1;for(let i=buf.length-22;i>=Math.max(0,buf.length-66000);i--){if(buf.readUInt32LE(i)===0x06054b50){eocd=i;break}}if(eocd<0)error('ZIP inválido.');const entries=buf.readUInt16LE(eocd+10),cdOffset=buf.readUInt32LE(eocd+16);let ptr=cdOffset;for(let n=0;n<entries&&ptr+46<=buf.length;n++){if(buf.readUInt32LE(ptr)!==0x02014b50)break;const flags=buf.readUInt16LE(ptr+8),method=buf.readUInt16LE(ptr+10),csize=buf.readUInt32LE(ptr+20),usize=buf.readUInt32LE(ptr+24),fn=buf.readUInt16LE(ptr+28),ex=buf.readUInt16LE(ptr+30),cm=buf.readUInt16LE(ptr+32),local=buf.readUInt32LE(ptr+42),name=buf.subarray(ptr+46,ptr+46+fn).toString('utf8');ptr+=46+fn+ex+cm;if(!/\.(ttf|otf|tff)$/i.test(name))continue;if(flags&1)error('La fuente dentro del ZIP está cifrada.');if(local+30>buf.length||buf.readUInt32LE(local)!==0x04034b50)error('ZIP inválido.');const lfn=buf.readUInt16LE(local+26),lex=buf.readUInt16LE(local+28),start=local+30+lfn+lex,end=start+csize;if(end>buf.length)error('ZIP inválido.');let out;if(method===0)out=buf.subarray(start,end);else if(method===8){try{out=zlib.inflateRawSync(buf.subarray(start,end),{maxOutputLength:2200000})}catch{error('No se pudo descomprimir la fuente del ZIP.')}}else error('El ZIP usa una compresión no compatible.');if(usize&&out.length!==usize)error('La fuente del ZIP está dañada.');validFontBytes(out);return {buffer:out,name:safeFontName(name),mime:/\.otf$/i.test(name)?'font/otf':'font/ttf'}}error('El ZIP no contiene una fuente .ttf u .otf.')}
function parseFontUpload(data,name){if(typeof data!=='string'||data.length>3800000)error('La fuente es demasiado grande.');const m=data.match(/^data:([^;,]+)?;base64,([A-Za-z0-9+/=]+)$/);if(!m)error('Archivo de fuente inválido.');const buf=Buffer.from(m[2],'base64'),filename=safeFontName(name);if(/\.zip$/i.test(filename)||/zip/i.test(m[1]||''))return extractFontFromZip(buf);validFontBytes(buf);return {buffer:buf,name:filename,mime:/\.otf$/i.test(filename)||/otf/i.test(m[1]||'')?'font/otf':'font/ttf'}}
function sendFont(res,row){res.writeHead(200,{'Content-Type':row.mime||'font/ttf','Cache-Control':'private, max-age=86400','X-Content-Type-Options':'nosniff'});res.end(Buffer.from(row.data,'base64'))}
async function chatProfileChanged(id){const user=await getUser(id);if(!user)return;const update={type:'profile',user:profile(user)};for(const code of chatStreams.keys()){try{const r=await room(code);if(r.members.some(m=>m.id===id))chatBroadcast(code,update)}catch{}}}
function adjustment(v={}){const result={};for(const k of ['avatar','frame','token']){const a=v[k]||{};result[k]={scale:Math.max(k==='avatar'?1:.5,Math.min(3,Number(a.scale)||1)),x:Math.max(-70,Math.min(70,Number(a.x)||0)),y:Math.max(-70,Math.min(70,Number(a.y)||0))}}return result}
const labels={avatar:'foto',frame:'marco',token:'ficha'};
async function capacity(id){const n=Number((await db.prepare('SELECT count(*) AS n FROM assets WHERE user_id=?').get(id)).n);if(n>=20)error('Tu armario tiene 20 imágenes. Reemplaza o borra una para guardar otra.')}
async function ownedAsset(id,userId){const item=await db.prepare('SELECT * FROM assets WHERE id=? AND user_id=?').get(String(id||''),userId);if(!item)error('No existe esa imagen en tu armario.',404);return item}
async function wardrobe(id){const rows=await db.prepare('SELECT id,kind,name,adjust,version FROM assets WHERE user_id=? ORDER BY name,id').all(id);return rows.map(r=>({...r,adjust:JSON.parse(r.adjust),url:`/api/wardrobe/${r.id}/image?v=${r.version}`}))}
async function chatProfile(user){const p=JSON.parse(user.profile),stickers=await db.prepare('SELECT id,created,last_used,use_count FROM stickers WHERE user_id=? ORDER BY last_used DESC,created DESC LIMIT 40').all(user.id);return {recentEmojis:Array.isArray(p.recentEmojis)?p.recentEmojis.slice(0,24):[],chatStyle:chatStyle(p.chatStyle),chatFont:chatFontMeta(p,user.id),stickers:stickers.map(x=>({...x,url:`/api/chat/stickers/${x.id}/image?v=${x.last_used||x.created}`})),stickerLimit:40}}
async function rememberEmoji(user,emoji){emoji=String(emoji||'').trim();if(!emoji||emoji.length>32||/\s/.test(emoji))error('Emoji inválido.');const p=JSON.parse(user.profile),list=[emoji,...(Array.isArray(p.recentEmojis)?p.recentEmojis:[]).filter(x=>x!==emoji)].slice(0,24);p.recentEmojis=list;await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(p),user.id);return list}
async function chatMessages(code){const rows=await db.prepare('SELECT id,user_id,kind,text,sticker_id,created FROM room_messages WHERE room=? ORDER BY created DESC,id DESC LIMIT 120').all(code);return rows.reverse().map(r=>({id:r.id,userId:r.user_id,kind:r.kind,text:r.text||'',stickerId:r.sticker_id||null,created:Number(r.created)}))}
function chatBroadcast(code,message){const data=`data: ${JSON.stringify(message)}\n\n`;for(const client of chatStreams.get(code)||[])client.write(data)}
function sendImage(res,data){const [head,encoded]=data.split(',');res.writeHead(200,{'Content-Type':head.slice(5,-7),'Cache-Control':'private, max-age=3600'});res.end(Buffer.from(encoded,'base64'))}
async function profileChanged(id){for(const code of streams.keys()){const r=await room(code);if(r.members.some(m=>m.id===id)){await save(r);await broadcast(r)}}}
// Preserve profiles created locally in v0.6, moving inline images out of player snapshots.
for(const user of await db.prepare('SELECT id,profile FROM users').all()){const p=JSON.parse(user.profile);if(['avatar','frame','token'].some(k=>p[k]))await db.transaction(async()=>{p.assetIds=p.assetIds||{};for(const k of ['avatar','frame','token'])if(p[k]){const id=uid();await db.prepare('INSERT INTO assets VALUES(?,?,?,?,?,?,?)').run(id,user.id,k,'Mi '+labels[k],p[k],JSON.stringify(p.adjust[k]),1);p.assetIds[k]=id;delete p[k]}await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(p),user.id)})}
let tail=Promise.resolve();
async function lock(){const previous=tail;let release;tail=new Promise(r=>release=r);await previous;return release}
const server=http.createServer(async(req,res)=>{let release;try{
res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');
res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; media-src 'self' blob:; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");
const url=new URL(req.url,'http://localhost'),p=url.pathname,post=req.method==='POST';
if(post&&req.headers.origin){const allowed=PUBLIC_URL?new URL(PUBLIC_URL).origin:`http://${req.headers.host}`;if(req.headers.origin!==allowed)error('Origen no permitido.',403)}
if(post){req.payload=await body(req);release=await lock()}
if(p==='/health'){send(res,200,{ok:true});return}
if(p==='/api/register'||p==='/api/login'){if(!post)error('Método inválido.',405);throttle(req);const b=await body(req,10000),username=String(b.username||'').toLowerCase().trim(),password=String(b.password||'');if(!/^[a-z0-9_]{3,24}$/.test(username)||password.length<8||password.length>128)error('Usuario: 3–24 letras, números o _. Contraseña: 8–128 caracteres.');let u=(await db.prepare('SELECT * FROM users WHERE username=?').get(username));if(p==='/api/register'){if(u)error('Ese usuario ya existe.');const salt=uid(),id=uid();(await db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(id,username,scryptSync(password,salt,64).toString('hex'),salt,JSON.stringify({name:username,version:1,adjust:adjustment(),chatStyle:chatStyle()})));u=await getUser(id)}else{const computed=scryptSync(password,u?.salt||'unknown',64);if(!u||!timingSafeEqual(computed,Buffer.from(u.hash,'hex')))error('Usuario o contraseña incorrectos.',401)}const token=randomBytes(32).toString('hex');(await db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),u.id,Date.now()+604800000));cookie(req,res,token);send(res,200,{user:profile(u)});return}
if(p.startsWith('/api/')){
const u=await auth(req);
if(p==='/api/me'&&!post){send(res,200,{user:profile(u)});return}
if(p==='/api/chat/profile'&&!post){send(res,200,await chatProfile(u));return}
if(p==='/api/chat/style'&&post){const b=await body(req,6000),v=JSON.parse(u.profile);v.chatStyle=chatStyle(b);v.version=(Number(v.version)||1)+1;await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(v),u.id);await chatProfileChanged(u.id);send(res,200,{chatStyle:v.chatStyle,user:profile(await getUser(u.id))});return}
if(p==='/api/chat/font'&&post){const b=await body(req,4200000),v=JSON.parse(u.profile);if(b.remove){await db.prepare('DELETE FROM chat_fonts WHERE user_id=?').run(u.id);delete v.chatFont;v.version=(Number(v.version)||1)+1;await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(v),u.id);await chatProfileChanged(u.id);send(res,200,{chatFont:null,user:profile(await getUser(u.id))});return}const parsed=parseFontUpload(b.data,b.name),now=Date.now();await db.transaction(async()=>{await db.prepare('INSERT INTO chat_fonts(user_id,name,mime,data,updated) VALUES(?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET name=excluded.name,mime=excluded.mime,data=excluded.data,updated=excluded.updated').run(u.id,parsed.name,parsed.mime,parsed.buffer.toString('base64'),now);v.chatFont={name:parsed.name,version:now};v.version=(Number(v.version)||1)+1;await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(v),u.id)});await chatProfileChanged(u.id);send(res,200,{chatFont:chatFontMeta(v,u.id),user:profile(await getUser(u.id))});return}
if(p==='/api/chat/emoji'&&post){const b=await body(req,2000);send(res,200,{recentEmojis:await rememberEmoji(u,b.emoji)});return}
if(p==='/api/chat/stickers'&&post){const b=await body(req,2300000),count=Number((await db.prepare('SELECT count(*) AS n FROM stickers WHERE user_id=?').get(u.id)).n);if(count>=40)error('Llegaste al límite de 40 stickers guardados.');const data=image(b.data,'sticker');if(!data)error('Sube una imagen para crear el sticker.');const id=uid(),now=Date.now();await db.prepare('INSERT INTO stickers VALUES(?,?,?,?,?,?)').run(id,u.id,data,now,now,0);send(res,201,{id,url:`/api/chat/stickers/${id}/image?v=${now}`,created:now,last_used:now,use_count:0});return}
const stickerImage=p.match(/^\/api\/chat\/stickers\/([a-f0-9]{32})\/image$/);if(stickerImage&&!post){const item=await db.prepare('SELECT data FROM stickers WHERE id=?').get(stickerImage[1]);if(!item)error('Ese sticker ya no existe.',404);sendImage(res,item.data);return}
const chatFontRoute=p.match(/^\/api\/users\/([a-f0-9]+)\/chat-font$/);if(chatFontRoute&&!post){const target=await getUser(chatFontRoute[1]);if(!target)error('No existe.',404);const row=await db.prepare('SELECT mime,data FROM chat_fonts WHERE user_id=?').get(target.id);if(!row)error('Esa persona no tiene fuente personalizada.',404);sendFont(res,row);return}
if(p==='/api/editor/board'&&!post){const stored=await savedBoard(u.id);send(res,200,{board:stored||defaultBoard,saved:!!stored});return}
if(p==='/api/editor/board'&&post){const b=await body(req);if(!b.board)error('Falta el tablero.');const next=checkedBoard(b.board),encoded=JSON.stringify(next),now=Date.now();if(encoded.length>65000000)error('El tablero supera el límite permitido.',413);await db.prepare('INSERT INTO board_configs(user_id,board,updated) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET board=excluded.board,updated=excluded.updated').run(u.id,encoded,now);const waiting=await db.prepare('SELECT code FROM rooms WHERE host=? AND state=?').all(u.id,'null');for(const row of waiting){await db.prepare('UPDATE rooms SET board=? WHERE code=?').run(encoded,row.code);boards.delete(row.code)}send(res,200,{ok:true,updated:now,waitingRoomsUpdated:waiting.length});return}
if(p==='/api/logout'&&post){const token=(req.headers.cookie||'').match(/kaoru=([a-f0-9]{64})/)?.[1];(await db.prepare('DELETE FROM sessions WHERE token=?').run(hash(token)));cookie(req,res,'',0);send(res,200,{ok:true});return}
if(p==='/api/profile'&&post){const b=await body(req,6500000),old=JSON.parse(u.profile);const name=String(b.name||u.username).trim();if(name.length<1||name.length>30)error('El nombre debe tener entre 1 y 30 caracteres.');const v={...old,name,assetIds:{...old.assetIds},adjust:adjustment(b.adjust),version:old.version+1};
// Validate every upload before starting an atomic write.
for(const k of ['avatar','frame','token'])if(Object.hasOwn(b,k))image(b[k],k);
await db.transaction(async()=>{for(const k of ['avatar','frame','token']){if(Object.hasOwn(b,k)){if(b[k]===null){delete v.assetIds[k];continue}let id=v.assetIds[k];if(!id){await capacity(u.id);id=uid();await db.prepare('INSERT INTO assets VALUES(?,?,?,?,?,?,?)').run(id,u.id,k,'Mi '+labels[k],b[k],JSON.stringify(v.adjust[k]),1)}else await db.prepare('UPDATE assets SET data=?,adjust=?,version=version+1 WHERE id=? AND user_id=?').run(b[k],JSON.stringify(v.adjust[k]),id,u.id);v.assetIds[k]=id}else if(v.assetIds[k])await db.prepare('UPDATE assets SET adjust=? WHERE id=? AND user_id=?').run(JSON.stringify(v.adjust[k]),v.assetIds[k],u.id)}await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(v),u.id)});await profileChanged(u.id);send(res,200,{user:profile(await getUser(u.id))});return}
if(p==='/api/wardrobe'&&!post){send(res,200,{items:await wardrobe(u.id),limit:20});return}
if(p==='/api/wardrobe/save'&&post){const b=await body(req,2300000);if(!['avatar','frame','token'].includes(b.kind))error('Tipo de imagen inválido.');const name=String(b.name||'').trim();if(!name||name.length>35)error('Pon un nombre de hasta 35 caracteres.');const old=b.id?await ownedAsset(b.id,u.id):null;if(old&&old.kind!==b.kind)error('No puedes cambiar el tipo de una imagen guardada.');const data=Object.hasOwn(b,'data')?image(b.data,b.kind):old?.data;if(!data)error('Sube una imagen.');const a=adjustment({[b.kind]:b.adjust||JSON.parse(old?.adjust||'{}')})[b.kind],id=old?.id||uid();if(!old)await capacity(u.id);const userProfile=JSON.parse(u.profile);
await db.transaction(async()=>{if(old)await db.prepare('UPDATE assets SET name=?,data=?,adjust=?,version=version+1 WHERE id=? AND user_id=?').run(name,data,JSON.stringify(a),id,u.id);else await db.prepare('INSERT INTO assets VALUES(?,?,?,?,?,?,?)').run(id,u.id,b.kind,name,data,JSON.stringify(a),1);if(userProfile.assetIds?.[b.kind]===id){userProfile.adjust[b.kind]=a;userProfile.version++;await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(userProfile),u.id)}});await profileChanged(u.id);send(res,200,{items:await wardrobe(u.id),user:profile(await getUser(u.id)),id});return}
if(p==='/api/wardrobe/equip'&&post){const b=await body(req,10000),item=await ownedAsset(b.id,u.id),v=JSON.parse(u.profile);v.assetIds={...v.assetIds,[item.kind]:item.id};v.adjust[item.kind]=JSON.parse(item.adjust);v.version++;await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(v),u.id);await profileChanged(u.id);send(res,200,{user:profile(await getUser(u.id))});return}
if(p==='/api/wardrobe/delete'&&post){const b=await body(req,10000),item=await ownedAsset(b.id,u.id),v=JSON.parse(u.profile);await db.transaction(async()=>{await db.prepare('DELETE FROM assets WHERE id=? AND user_id=?').run(item.id,u.id);if(v.assetIds?.[item.kind]===item.id){delete v.assetIds[item.kind];v.version++;await db.prepare('UPDATE users SET profile=? WHERE id=?').run(JSON.stringify(v),u.id)}});await profileChanged(u.id);send(res,200,{items:await wardrobe(u.id),user:profile(await getUser(u.id))});return}
const wa=p.match(/^\/api\/wardrobe\/([a-f0-9]{32})\/image$/);if(wa&&!post){const item=await ownedAsset(wa[1],u.id);sendImage(res,item.data);return}
const am=p.match(/^\/api\/users\/([a-f0-9]+)\/assets\/(avatar|frame|token)$/);if(am&&!post){const target=await getUser(am[1]);if(!target)error('No existe.',404);const id=JSON.parse(target.profile).assetIds?.[am[2]],item=id?await db.prepare('SELECT data FROM assets WHERE id=? AND user_id=?').get(id,target.id):null;if(!item)error('No hay imagen.',404);sendImage(res,item.data);return}
if(p==='/api/rooms'&&!post){const rows=(await db.prepare('SELECT code,host,members,state FROM rooms').all()).filter(r=>JSON.parse(r.members).some(m=>m.id===u.id));send(res,200,{rooms:rows.map(r=>({code:r.code,started:!!JSON.parse(r.state),finished:JSON.parse(r.state)?.phase==='finished'}))});return}
if(p==='/api/rooms'&&post){const b=await body(req);const board=b.board?checkedBoard(b.board):(await savedBoard(u.id))||structuredClone(defaultBoard);const count=(await db.prepare('SELECT count(*) AS n FROM rooms WHERE host=?').get(u.id)).n;if(count>=50)error('Llegaste al límite de 50 salas. Elimina salas antiguas desde el servidor.');let code;do{code=randomBytes(4).toString('hex').slice(0,6).toUpperCase()}while((await db.prepare('SELECT code FROM rooms WHERE code=?').get(code)));const settings={pot:!!b.pot,rounds:b.rounds===0?0:Math.max(5,Math.min(100,Number(b.rounds)||30)),musicOrder:musicOrder(),musicEpoch:Date.now()};(await db.prepare('INSERT INTO rooms VALUES(?,?,?,?,?,?,?)').run(code,u.id,JSON.stringify(board),JSON.stringify([{id:u.id,ready:false}]),JSON.stringify(settings),'null',1));send(res,201,await snapshot(await room(code)));return}
const chat=p.match(/^\/api\/rooms\/([A-Z0-9]{6})\/chat(?:\/(events))?$/);if(chat){const r=await room(chat[1]);member(r,u);if(chat[2]==='events'&&!post){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});if(!chatStreams.has(r.code))chatStreams.set(r.code,new Set());chatStreams.get(r.code).add(res);res.write(': connected\n\n');const heartbeat=setInterval(()=>res.write(': ping\n\n'),20000);req.on('close',()=>{clearInterval(heartbeat);chatStreams.get(r.code)?.delete(res);if(!chatStreams.get(r.code)?.size)chatStreams.delete(r.code)});return}if(!post){send(res,200,{messages:await chatMessages(r.code)});return}const b=await body(req,2300000),kind=b.stickerId?'sticker':'text',text=String(b.text||'').trim();let stickerId=null;if(kind==='text'){if(!text)error('Escribe un mensaje.');if(text.length>500)error('El mensaje no puede superar 500 caracteres.')}else{stickerId=String(b.stickerId||'');const sticker=await db.prepare('SELECT id FROM stickers WHERE id=? AND user_id=?').get(stickerId,u.id);if(!sticker)error('Ese sticker no está en tu perfil.',404);const now=Date.now();await db.prepare('UPDATE stickers SET last_used=?,use_count=use_count+1 WHERE id=? AND user_id=?').run(now,stickerId,u.id)}const message={id:uid(),userId:u.id,kind,text:kind==='text'?text:'',stickerId,style:chatStyle(JSON.parse(u.profile).chatStyle),created:Date.now()};await db.prepare('INSERT INTO room_messages VALUES(?,?,?,?,?,?,?)').run(message.id,r.code,u.id,message.kind,message.text,message.stickerId,message.created);await db.prepare('DELETE FROM room_messages WHERE room=? AND id NOT IN (SELECT id FROM room_messages WHERE room=? ORDER BY created DESC,id DESC LIMIT 300)').run(r.code,r.code);chatBroadcast(r.code,message);send(res,201,{message});return}
const rm=p.match(/^\/api\/rooms\/([A-Z0-9]{6})(?:\/(join|ready|start|action|events|board))?$/);if(rm){let r=await room(rm[1]);const op=rm[2];if(op==='join'&&post){let changed=false;if(!r.members.some(m=>m.id===u.id)){if(r.state)error('La partida ya comenzó.');if(r.members.length>=4)error('La sala está llena.');r.members.push({id:u.id,ready:false});await save(r);changed=true}const snap=await snapshot(r);if(changed)await broadcast(r,snap);send(res,200,snap);return}member(r,u);
if(op==='events'&&!post){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});if(!streams.has(r.code))streams.set(r.code,new Set());streams.get(r.code).add(res);res.write(`id: ${r.revision}\ndata: ${JSON.stringify(await snapshot(r))}\n\n`);const heartbeat=setInterval(()=>res.write(': ping\n\n'),20000);req.on('close',()=>{clearInterval(heartbeat);streams.get(r.code)?.delete(res);if(!streams.get(r.code)?.size)streams.delete(r.code)});return}
if(op==='board'&&!post){send(res,200,r.board);return}if(!op&&!post){send(res,200,await snapshot(r));return}
if(!post)error('Método inválido.',405);const b=await body(req,20000);r=await room(rm[1]);member(r,u);
if(op==='ready'){if(r.state)error('La partida ya comenzó.');r.members.find(m=>m.id===u.id).ready=!!b.ready}
else if(op==='start'){if(r.host!==u.id||r.state)error('Solo la anfitriona puede iniciar una partida nueva.',403);if(r.members.length<2||!r.members.every(m=>m.ready))error('Se necesitan de 2 a 4 jugadoras y todas listas.');r.state=Game.create(r.members.map(m=>m.id),r.settings)}
else if(op==='action'){if(!r.state)error('La partida no comenzó.');if(typeof b.actionId!=='string'||!/^[a-zA-Z0-9-]{8,80}$/.test(b.actionId))error('Identificador de acción inválido.');if((await db.prepare('SELECT 1 FROM actions WHERE room=? AND user_id=? AND action_id=?').get(r.code,u.id,b.actionId))){send(res,200,await snapshot(r));return}if(b.revision!==r.revision)error('La partida cambió. Intenta de nuevo.',409);if(!b.action||typeof b.action.type!=='string')error('Acción inválida.');Game.act(r.state,r.board,u.id,b.action);await db.transaction(async()=>{(await db.prepare('INSERT INTO actions VALUES(?,?,?)').run(r.code,u.id,b.actionId));await save(r)});const snap=await snapshot(r);await broadcast(r,snap);send(res,200,snap);return}
else error('Ruta no encontrada.',404);await save(r);const snap=await snapshot(r);await broadcast(r,snap);send(res,200,snap);return}
error('Ruta no encontrada.',404)}
if(req.method!=='GET'&&req.method!=='HEAD')error('Método inválido.',405);
let relative=decodeURIComponent(p);if(relative.endsWith('/'))relative+='index.html';const filename=path.resolve(ROOT,'public','.'+relative);if(!filename.startsWith(path.join(ROOT,'public')+path.sep)||relative.split('/').some(x=>x.startsWith('.')))error('No encontrado.',404);let stat;try{stat=fs.statSync(filename)}catch{error('No encontrado.',404)}if(!stat.isFile())error('No encontrado.',404);const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4','.mp3':'audio/mpeg','.wav':'audio/wav','.ttf':'font/ttf'};const ext=path.extname(filename);const cache=['.png','.webp','.mp4','.mp3','.wav','.ttf'].includes(ext)?'public, max-age=86400':'no-cache';res.writeHead(200,{'Content-Type':mime[ext]||'application/octet-stream','Cache-Control':cache});if(req.method==='HEAD')res.end();else fs.createReadStream(filename).pipe(res);
}catch(e){if(!res.headersSent)send(res,e.status||400,{error:e.status===500?'Error del servidor.':e.message});else res.end()}finally{release?.()}});
let ticking=false;
const timer=setInterval(async()=>{if(ticking||!streams.size)return;ticking=true;let release;try{release=await lock();for(const row of await db.prepare("SELECT code FROM rooms WHERE json_extract(state,'$.phase')='auction'").all()){const r=await room(row.code);if(r.state.phase==='auction'&&Date.now()>=r.state.auction.until){Game.resolveAuction(r.state,r.board);await save(r);await broadcast(r)}}}catch{console.error('No se pudo cerrar una subasta; se reintentará.')}finally{release?.();ticking=false}},2000);timer.unref();
server.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log(`Kaoru listo en http://localhost:${server.address().port}`));
process.on('SIGTERM',()=>{clearInterval(timer);for(const ss of streams.values())for(const s of ss)s.end();for(const ss of chatStreams.values())for(const s of ss)s.end();server.close(async()=>{await db.close();process.exit(0)})});

}
main().catch(()=>{console.error("No se pudo iniciar Kaoru. Revisa DATABASE_URL, la conexión y el certificado de la base de datos.");process.exit(1)});
