const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const M=require('../board-model.js');
test('40 unique perimeter cells, 11 per side, exact middle stations',()=>{const cells=M.tiles().map(t=>M.coords(t.position));assert.equal(new Set(cells.map(x=>x.join(','))).size,40);for(const [r,c]of cells)assert(r===1||r===11||c===1||c===11);for(const axis of [0,1])for(const edge of [1,11])assert.equal(cells.filter(p=>p[axis]===edge).length,11);assert.deepEqual([5,15,25,35].map(M.coords),[[11,6],[6,1],[1,6],[6,11]])});
test('all classic cell types and group counts',()=>{const counts={};for(const t of M.tiles())counts[t.type]=(counts[t.type]||0)+1;assert.deepEqual(counts,{go:1,street:22,community:3,tax:2,transport:4,chance:3,jail:1,utility:2,parking:1,goToJail:1});assert.deepEqual(M.groupSizes,[2,3,3,3,3,3,3,2]);M.validate(M.initial())});
test('v2 migration preserves all twenty artworks, names, crops and economic values',()=>{const base=M.initial();const old={version:2,title:'Original',layout:'compact-28',ruleset:'kaoru-proposal',streets:base.streets.slice(0,20)};old.streets[0].image='data:image/png;base64,AAAA';const before=JSON.stringify(old);const converted=M.migrate(old);M.validate(converted);assert.equal(JSON.stringify(old),before);assert.equal(converted.streets.length,22);for(let i=0;i<20;i++)for(const key of ['name','image','series','price','rent','groupRent','buildCost','upgradeRents','zoom','x','y'])assert.deepEqual(converted.streets[i][key],old.streets[i][key])});
test('included user board has 22 streets and 19 images; default script matches JSON',()=>{const b=JSON.parse(fs.readFileSync(path.join(__dirname,'../kaoru-tablero-40.json')));M.validate(b);assert.equal(b.streets.filter(x=>x.image).length,19);assert.equal(b.streets[0].name,'Winx Club');assert.equal(b.streets[19].name,'Arcane');const script=fs.readFileSync(path.join(__dirname,'../default-board.js'),'utf8');assert.deepEqual(JSON.parse(script.slice(script.indexOf('=')+1).trim().replace(/;$/,'')),b)});
test('unsafe images, invalid groups and declining upgrades are rejected',()=>{for(const patch of [{image:'https://x.test/a.png'},{groupId:8},{price:-1},{zoom:0},{upgradeRents:[30,20,40,50,60]}]){const b=M.initial();Object.assign(b.streets[0],patch);assert.throws(()=>M.validate(b))}});
test('crop completely covers square at every zoom without stretching artwork',()=>{for(const [iw,ih]of [[900,400],[300,900],[400,400]])for(const zoom of [1,2,4])for(const x of [0,.5,1]){const [dx,dy,w,h]=M.cropRect(iw,ih,600,600,zoom,x,.75);assert(dx<=0&&dy<=0);assert(dx+w>=600-1e-8&&dy+h>=600-1e-8);assert(Math.abs(w/h-iw/ih)<1e-8)}});
test('36 editable images total, with exactly 14 special spaces and no corners',()=>{const b=M.initial();assert.equal(b.streets.length+Object.keys(b.specialArtwork).length,36);assert.deepEqual(M.imagePositions,[2,4,5,7,12,15,17,22,25,28,33,35,36,38]);for(const p of [0,10,20,30])assert.equal(b.specialArtwork[p],undefined);const bad=structuredClone(b);bad.specialArtwork[0]={image:null,zoom:1,x:.5,y:.5};assert.throws(()=>M.validate(bad))});
test('v3 upgrade preserves streets and special-image crops survive JSON roundtrip',()=>{const old=M.initial();old.version=3;delete old.specialArtwork;const before=JSON.stringify(old);const b=M.migrate(old);assert.deepEqual(b.streets,old.streets);assert.equal(JSON.stringify(old),before);b.specialArtwork[2]={image:'data:image/png;base64,AAAA',zoom:2.1,x:.2,y:.7};const copy=JSON.parse(JSON.stringify(b));M.validate(copy);assert.deepEqual(copy.specialArtwork[2],b.specialArtwork[2]);copy.specialArtwork[2].image='javascript:alert(1)';assert.throws(()=>M.validate(copy))});
