const {test}=require('node:test'),assert=require('node:assert/strict');
const G=require('../game.cjs'),M=require('../public/editor/board-model.js');
const board=M.initial(),newGame=()=>G.create(['a','b','c'],{rounds:30,pot:true});
function roll(g,id,x){G.act(g,board,id,{type:'roll'},()=>x-1)}
test('GO starts bottom left, all 40 unique cells and grouped property order',()=>{assert.deepEqual(M.coords(0),[11,1]);assert.deepEqual(M.coords(1),[10,1]);assert.equal(new Set(M.tiles().map(t=>M.coords(t.position).join(','))).size,40);M.validate(board)});
test('one die movement, buying and rent auto-finish turns',()=>{const g=newGame();assert.deepEqual(g.dice,[1]);assert.equal(g.players[0].cash,1300);roll(g,'a',1);assert.equal(g.players[0].pos,1);assert.equal(g.phase,'buy');G.act(g,board,'a',{type:'buy'});assert.equal(g.owners[1].id,'a');assert.equal(g.turn,1);assert.equal(g.phase,'roll');roll(g,'b',1);assert.equal(g.players[1].cash,1300-board.streets[0].rent*2);assert.equal(g.players[0].cash,1300-60+board.streets[0].rent*2);assert.equal(g.turn,2);assert.equal(g.phase,'roll')});
test('passing GO pays 150 and go-to-jail never pays GO',()=>{const g=newGame();g.players[0].pos=39;roll(g,'a',1);assert.equal(g.players[0].pos,0);assert.equal(g.players[0].cash,1450);g.turn=0;g.phase='roll';g.players[0].pos=29;roll(g,'a',1);assert.equal(g.players[0].pos,10);assert.equal(g.players[0].jail,3);assert.equal(g.players[0].cash,1450)});
test('jail costs 150, exits on 6, and third failed attempt pays automatically',()=>{const g=newGame();g.players[0].pos=10;g.players[0].jail=3;for(let i=0;i<2;i++){g.turn=0;g.phase='roll';roll(g,'a',2);assert.equal(g.players[0].pos,10)}g.turn=0;g.phase='roll';roll(g,'a',3);assert.equal(g.players[0].pos,13);assert.equal(g.players[0].cash,1150);g.turn=0;g.phase='roll';g.players[0].pos=10;g.players[0].jail=2;roll(g,'a',6);assert.equal(g.players[0].jail,0);assert.equal(g.players[0].pos,16);const h=newGame();h.players[0].jail=2;h.players[0].cash=149;assert.throws(()=>G.act(h,board,'a',{type:'release',method:'pay'}),/150/);h.players[0].cash=150;G.act(h,board,'a',{type:'release',method:'pay'});assert.equal(h.players[0].cash,0);assert.equal(h.players[0].jail,0)});
test('building needs full group, balanced levels; mortgages stop doubled rent',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};assert.throws(()=>G.act(g,board,'a',{type:'build',position:1}),/grupo/);g.owners[3]={id:'a',level:0,mortgaged:false};G.act(g,board,'a',{type:'build',position:1});assert.throws(()=>G.act(g,board,'a',{type:'build',position:1}),/equilibrada/);assert.throws(()=>G.act(g,board,'a',{type:'mortgage',position:3}),/edificios/);G.act(g,board,'a',{type:'sellBuilding',position:1});G.act(g,board,'a',{type:'mortgage',position:1});assert.equal(G.rent(g,board,1,4),0);assert.equal(G.rent(g,board,3,4),board.streets[1].rent*2);g.owners[12]={id:'b',level:0,mortgaged:false};assert.equal(G.rent(g,board,12,4),64);g.owners[28]={id:'b',level:0,mortgaged:false};assert.equal(G.rent(g,board,12,4),160)});
test('passing a free property keeps it free and manual auctions are rejected',()=>{const g=newGame();roll(g,'a',1);assert.equal(g.phase,'buy');assert.throws(()=>G.act(g,board,'a',{type:'auction'}),/ya no se subastan/);G.act(g,board,'a',{type:'passBuy'});assert.equal(g.owners[1],undefined);assert.equal(g.turn,1);assert.equal(g.phase,'roll')});
test('debt pays only available funds, debtor can mortgage outside own turn',()=>{const g=newGame();g.players[1].cash=10;g.owners[1]={id:'b',level:0,mortgaged:false};g.debts=[{from:'b',to:'a',amount:25}];g.phase='debt';g.resume='end';G.act(g,board,'b',{type:'mortgage',position:1});assert.equal(g.players[0].cash,1325);assert.equal(g.players[1].cash,15);assert.equal(g.debts.length,0);assert.equal(g.phase,'end')});
test('out current player cannot trap turn after another player settles debt',()=>{const g=newGame();g.players[1].cash=0;g.owners[1]={id:'b',level:0,mortgaged:false};g.debts=[{from:'b',to:'bank',amount:25}];g.phase='debt';g.resume='end';G.act(g,board,'a',{type:'resign'});G.act(g,board,'b',{type:'mortgage',position:1});assert.equal(g.turn,1);assert.equal(g.phase,'roll')});
test('stronger taxes fill the optional parking pot and parking pays it',()=>{const g=newGame();roll(g,'a',4);assert.equal(g.pot,300);assert.equal(g.players[0].cash,1000);g.turn=0;g.phase='roll';g.players[0].pos=19;roll(g,'a',1);assert.equal(g.pot,0);assert.equal(g.players[0].cash,1300)});
test('chance jail and backward cards resolve destinations with stronger penalties',()=>{const g=newGame();g.players[0].pos=6;g.decks.chance=[3];roll(g,'a',1);assert.equal(g.players[0].jail,3);assert.match(g.event.text,/cárcel/);const h=newGame();h.players[0].pos=6;h.decks.chance=[0];roll(h,'a',1);assert.equal(h.players[0].pos,4);assert.equal(h.players[0].cash,1000)});
test('one to one property swap requires recipient consent',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};g.owners[3]={id:'b',level:0,mortgaged:false};G.act(g,board,'a',{type:'offerTrade',to:'b',give:1,receive:3});assert.equal(g.owners[1].id,'a');assert.throws(()=>G.act(g,board,'c',{type:'acceptTrade'}),/Espera/);G.act(g,board,'b',{type:'acceptTrade'});assert.equal(g.owners[1].id,'b');assert.equal(g.phase,'roll')});
test('end of round cap compares net worth; resigning cannot create money',()=>{const g=G.create(['a','b'],{rounds:5});g.round=5;g.turn=1;g.phase='end';g.owners[1]={id:'a',level:0,mortgaged:false};G.act(g,board,'b',{type:'end'});assert.equal(g.phase,'finished');assert.deepEqual(g.winners,['a'])});


test('GO produces one bank reward effect and no mirrored deduction',()=>{const g=newGame();g.players[0].pos=39;roll(g,'a',1);assert.equal(g.players[0].cash,1450);assert.equal(g.bankFx.filter(x=>x.source==='go').length,1);assert.deepEqual(g.bankFx.filter(x=>x.source==='go').map(x=>[x.direction,x.amount]),[['give',150]]);assert.equal(g.bankFx.some(x=>x.direction==='take'&&x.amount===150),false)});
test('bank debt visual reports only money actually paid and is not duplicated',()=>{const g=newGame();g.players[0].cash=120;roll(g,'a',4);const takes=g.bankFx.filter(x=>x.direction==='take');assert.equal(takes.length,1);assert.equal(takes[0].amount,120);assert.equal(g.players[0].cash,0);assert.equal(g.debts[0].amount,180)});
test('player-to-player rent emits an explicit transfer visual',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};g.turn=1;g.phase='roll';roll(g,'b',1);const fx=g.bankFx.find(x=>x.source==='player');assert.ok(fx);assert.equal(fx.from,'b');assert.equal(fx.to,'a');assert.equal(fx.amount,board.streets[0].rent*2)});
test('money effects carry natural reasons for rent and purchases',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};g.turn=1;g.phase='roll';roll(g,'b',1);const rentFx=g.bankFx.find(x=>x.source==='player');assert.match(rentFx.reason,/por el alquiler de la propiedad/i);const h=newGame();roll(h,'a',1);G.act(h,board,'a',{type:'buy'});const buyFx=h.bankFx.find(x=>x.to==='bank');assert.match(buyFx.reason,/por comprar la propiedad/i)});
