const {test}=require('node:test'),assert=require('node:assert/strict');
const G=require('../game.cjs'),M=require('../public/editor/board-model.js');
const board=M.initial(),newGame=()=>G.create(['a','b','c'],{rounds:30,pot:true});
function roll(g,id,x,y){let i=0;G.act(g,board,id,{type:'roll'},()=>[x-1,y-1][i++%2])}
test('GO starts bottom left, all 40 unique cells and grouped property order',()=>{assert.deepEqual(M.coords(0),[11,1]);assert.deepEqual(M.coords(1),[10,1]);assert.equal(new Set(M.tiles().map(t=>M.coords(t.position).join(','))).size,40);M.validate(board)});
test('server dice movement, buying and paying rent transfer real money',()=>{const g=newGame();roll(g,'a',1,2);assert.equal(g.players[0].pos,3);assert.equal(g.phase,'buy');G.act(g,board,'a',{type:'buy'});assert.equal(g.owners[3].id,'a');G.act(g,board,'a',{type:'end'});roll(g,'b',1,2);assert.equal(g.players[1].cash,1500-board.streets[1].rent);assert.equal(g.players[0].cash,1500-60+board.streets[1].rent);assert.throws(()=>G.act(g,board,'c',{type:'end'}),/turno/)});
test('passing GO pays once, jail does not pay GO and three doubles jail',()=>{const g=newGame();g.players[0].pos=39;roll(g,'a',1,2);assert.ok(g.players[0].cash>=1700);g.phase='roll';g.players[0].pos=27;roll(g,'a',1,2);assert.equal(g.players[0].pos,10);assert.equal(g.players[0].jail,3);const h=newGame();h.doubles=2;roll(h,'a',2,2);assert.equal(h.players[0].pos,10);assert.equal(h.extra,false)});
test('jail failed rolls, mandatory third payment, held release card',()=>{const g=newGame();g.players[0].pos=10;g.players[0].jail=3;for(let i=0;i<2;i++){g.phase='roll';roll(g,'a',1,2);assert.equal(g.players[0].pos,10)}g.phase='roll';roll(g,'a',1,2);assert.equal(g.players[0].pos,13);assert.equal(g.players[0].cash,1450);g.players[0].jail=2;g.players[0].pass=1;g.phase='roll';G.act(g,board,'a',{type:'release',method:'card'});assert.equal(g.players[0].jail,0);assert.equal(g.players[0].pass,0)});
test('building needs full group, balanced levels; mortgages stop rent',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};assert.throws(()=>G.act(g,board,'a',{type:'build',position:1}),/grupo/);g.owners[3]={id:'a',level:0,mortgaged:false};G.act(g,board,'a',{type:'build',position:1});assert.throws(()=>G.act(g,board,'a',{type:'build',position:1}),/equilibrada/);assert.throws(()=>G.act(g,board,'a',{type:'mortgage',position:3}),/edificios/);G.act(g,board,'a',{type:'sellBuilding',position:1});G.act(g,board,'a',{type:'mortgage',position:1});assert.equal(G.rent(g,board,1,7),0);assert.equal(G.rent(g,board,3,7),board.streets[1].rent)});
test('auctions accept other players, reject unaffordable bids and assign once',()=>{const g=newGame();roll(g,'a',1,2);G.act(g,board,'a',{type:'auction'},undefined,1000);G.act(g,board,'b',{type:'bid',amount:100},undefined,1001);assert.throws(()=>G.act(g,board,'c',{type:'bid',amount:2000},undefined,1002),/Oferta/);G.act(g,board,'a',{type:'passAuction'},undefined,1003);G.act(g,board,'c',{type:'passAuction'},undefined,1004);assert.equal(g.owners[3].id,'b');assert.equal(g.players[1].cash,1400);assert.equal(g.phase,'end')});
test('debt pays only available funds, debtor can mortgage outside own turn',()=>{const g=newGame();g.players[1].cash=10;g.owners[1]={id:'b',level:0,mortgaged:false};g.debts=[{from:'b',to:'a',amount:25}];g.phase='debt';g.resume='end';G.act(g,board,'b',{type:'mortgage',position:1});assert.equal(g.players[0].cash,1525);assert.equal(g.players[1].cash,15);assert.equal(g.debts.length,0);assert.equal(g.phase,'end')});
test('out current player cannot trap turn after another player settles debt',()=>{const g=newGame();g.players[1].cash=0;g.owners[1]={id:'b',level:0,mortgaged:false};g.debts=[{from:'b',to:'bank',amount:25}];g.phase='debt';g.resume='end';G.act(g,board,'a',{type:'resign'});G.act(g,board,'b',{type:'mortgage',position:1});assert.equal(g.turn,1);assert.equal(g.phase,'roll')});
test('optional parking pot collects taxes and pays on landing only',()=>{const g=newGame();roll(g,'a',1,3);assert.equal(g.pot,200);assert.equal(g.players[0].cash,1300);g.phase='roll';g.players[0].pos=17;roll(g,'a',1,2);assert.equal(g.pot,0);assert.equal(g.players[0].cash,1500)});
test('chance jail and backward cards resolve destinations',()=>{const g=newGame();g.players[0].pos=4;g.decks.chance=[3];roll(g,'a',1,2);assert.equal(g.players[0].jail,3);assert.match(g.event.text,/cárcel/);const h=newGame();h.players[0].pos=4;h.decks.chance=[0];roll(h,'a',1,2);assert.equal(h.players[0].pos,4);assert.equal(h.players[0].cash,1300)});
test('one to one property swap requires recipient consent',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};g.owners[3]={id:'b',level:0,mortgaged:false};G.act(g,board,'a',{type:'offerTrade',to:'b',give:1,receive:3});assert.equal(g.owners[1].id,'a');assert.throws(()=>G.act(g,board,'c',{type:'acceptTrade'}),/Espera/);G.act(g,board,'b',{type:'acceptTrade'});assert.equal(g.owners[1].id,'b');assert.equal(g.phase,'roll')});
test('end of round cap compares net worth; resigning cannot create money',()=>{const g=G.create(['a','b'],{rounds:5});g.round=5;g.turn=1;g.phase='end';g.owners[1]={id:'a',level:0,mortgaged:false};G.act(g,board,'b',{type:'end'});assert.equal(g.phase,'finished');assert.deepEqual(g.winners,['a'])});
