const {test}=require('node:test'),assert=require('node:assert/strict');
const G=require('../game.cjs'),M=require('../public/editor/board-model.js');
const board=M.initial(),newGame=()=>G.create(['a','b','c'],{rounds:30,pot:true});
function roll(g,id,x){G.act(g,board,id,{type:'roll'},()=>x-1)}
test('GO starts bottom left, all 40 unique cells and grouped property order',()=>{assert.deepEqual(M.coords(0),[11,1]);assert.deepEqual(M.coords(1),[10,1]);assert.equal(new Set(M.tiles().map(t=>M.coords(t.position).join(','))).size,40);M.validate(board)});
test('one die movement, buying and rent auto-finish turns',()=>{const g=newGame();assert.deepEqual(g.dice,[1]);assert.equal(g.players[0].cash,1300);roll(g,'a',1);assert.equal(g.players[0].pos,1);assert.equal(g.phase,'buy');G.act(g,board,'a',{type:'buy'});assert.equal(g.owners[1].id,'a');assert.equal(g.turn,1);assert.equal(g.phase,'roll');roll(g,'b',1);assert.equal(g.players[1].cash,1300-board.streets[0].rent*3);assert.equal(g.players[0].cash,1300-60+board.streets[0].rent*3);assert.equal(g.turn,2);assert.equal(g.phase,'roll')});
test('passing GO pays 200 and go-to-jail stages prison transfer',()=>{const g=newGame();g.players[0].pos=39;roll(g,'a',1);assert.equal(g.players[0].pos,0);assert.equal(g.players[0].cash,1500);g.turn=0;g.phase='roll';g.players[0].pos=29;roll(g,'a',1);assert.equal(g.players[0].pos,30);assert.equal(g.players[0].jail,0);assert.equal(g.phase,'cardMove');G.act(g,board,'a',{type:'resolveCardMove'});assert.equal(g.players[0].pos,10);assert.equal(g.players[0].jail,3);assert.equal(g.players[0].cash,1500)});
test('jail costs 150, exits on 6, and third failed attempt pays automatically',()=>{const g=newGame();g.players[0].pos=10;g.players[0].jail=3;for(let i=0;i<2;i++){g.turn=0;g.phase='roll';roll(g,'a',2);assert.equal(g.players[0].pos,10)}g.turn=0;g.phase='roll';roll(g,'a',3);assert.equal(g.players[0].pos,13);assert.equal(g.players[0].cash,1150);g.turn=0;g.phase='roll';g.players[0].pos=10;g.players[0].jail=2;roll(g,'a',6);assert.equal(g.players[0].jail,0);assert.equal(g.players[0].pos,16);const h=newGame();h.players[0].jail=2;h.players[0].cash=149;assert.throws(()=>G.act(h,board,'a',{type:'release',method:'pay'}),/150/);h.players[0].cash=150;G.act(h,board,'a',{type:'release',method:'pay'});assert.equal(h.players[0].cash,0);assert.equal(h.players[0].jail,0)});
test('building needs full group, balanced levels; mortgages stop higher rent',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};assert.throws(()=>G.act(g,board,'a',{type:'build',position:1}),/grupo/);g.owners[3]={id:'a',level:0,mortgaged:false};G.act(g,board,'a',{type:'build',position:1});assert.throws(()=>G.act(g,board,'a',{type:'build',position:1}),/equilibrada/);assert.throws(()=>G.act(g,board,'a',{type:'mortgage',position:3}),/edificios/);G.act(g,board,'a',{type:'sellBuilding',position:1});G.act(g,board,'a',{type:'mortgage',position:1});assert.equal(G.rent(g,board,1,4),0);assert.equal(G.rent(g,board,3,4),board.streets[1].rent*3);g.owners[12]={id:'b',level:0,mortgaged:false};assert.equal(G.rent(g,board,12,4),80);g.owners[28]={id:'b',level:0,mortgaged:false};assert.equal(G.rent(g,board,12,4),200)});
test('passing a free property keeps it free and manual auctions are rejected',()=>{const g=newGame();roll(g,'a',1);assert.equal(g.phase,'buy');assert.throws(()=>G.act(g,board,'a',{type:'auction'}),/ya no se subastan/);G.act(g,board,'a',{type:'passBuy'});assert.equal(g.owners[1],undefined);assert.equal(g.turn,1);assert.equal(g.phase,'roll')});
test('debt pays only available funds, debtor can mortgage outside own turn',()=>{const g=newGame();g.players[1].cash=10;g.owners[1]={id:'b',level:0,mortgaged:false};g.debts=[{from:'b',to:'a',amount:25}];g.phase='debt';g.resume='end';G.act(g,board,'b',{type:'mortgage',position:1});assert.equal(g.players[0].cash,1325);assert.equal(g.players[1].cash,15);assert.equal(g.debts.length,0);assert.equal(g.phase,'end')});
test('out current player cannot trap turn after another player settles debt',()=>{const g=newGame();g.players[1].cash=0;g.owners[1]={id:'b',level:0,mortgaged:false};g.debts=[{from:'b',to:'bank',amount:25}];g.phase='debt';g.resume='end';G.act(g,board,'a',{type:'resign'});G.act(g,board,'b',{type:'mortgage',position:1});assert.equal(g.turn,1);assert.equal(g.phase,'roll')});
test('stronger taxes fill the optional parking pot and parking pays it',()=>{const g=newGame();roll(g,'a',4);assert.equal(g.pot,50);assert.equal(g.players[0].cash,1250);g.turn=0;g.phase='roll';g.players[0].pos=19;roll(g,'a',1);assert.equal(g.pot,0);assert.equal(g.players[0].cash,1300);assert.equal(g.visualEvents.some(e=>e.position===20),false);assert.equal(g.bankFx.some(e=>e.from==='pot'&&e.amount===50),true)});
test('chance jail and backward cards wait until cartilla is resolved',()=>{const g=newGame();g.players[0].pos=6;g.decks.chance=[3];roll(g,'a',1);assert.equal(g.players[0].pos,7);assert.equal(g.players[0].jail,0);assert.equal(g.phase,'cardMove');assert.match(g.event.text,/cárcel/);G.act(g,board,'a',{type:'resolveCardMove'});assert.equal(g.players[0].pos,10);assert.equal(g.players[0].jail,3);assert.equal(g.movement.teleport,true);const h=newGame();h.players[0].pos=6;h.decks.chance=[0];roll(h,'a',1);assert.equal(h.players[0].pos,7);assert.equal(h.phase,'cardMove');G.act(h,board,'a',{type:'resolveCardMove'});assert.equal(h.players[0].pos,4);assert.equal(h.players[0].cash,1250)});
test('one to one property swap requires recipient consent',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};g.owners[3]={id:'b',level:0,mortgaged:false};G.act(g,board,'a',{type:'offerTrade',to:'b',give:1,receive:3});assert.equal(g.owners[1].id,'a');assert.throws(()=>G.act(g,board,'c',{type:'acceptTrade'}),/Espera/);G.act(g,board,'b',{type:'acceptTrade'});assert.equal(g.owners[1].id,'b');assert.equal(g.phase,'roll')});
test('end of round cap compares net worth; resigning cannot create money',()=>{const g=G.create(['a','b'],{rounds:5});g.round=5;g.turn=1;g.phase='end';g.owners[1]={id:'a',level:0,mortgaged:false};G.act(g,board,'b',{type:'end'});assert.equal(g.phase,'finished');assert.deepEqual(g.winners,['a'])});


test('GO produces one 200 bank reward effect, no mirrored deduction and no popup card',()=>{const g=newGame();g.players[0].pos=39;roll(g,'a',1);assert.equal(g.players[0].cash,1500);assert.equal(g.bankFx.filter(x=>x.source==='go').length,1);assert.deepEqual(g.bankFx.filter(x=>x.source==='go').map(x=>[x.direction,x.amount]),[['give',200]]);assert.equal(g.bankFx.some(x=>x.direction==='take'&&x.amount===200),false);assert.equal(g.visualEvents.length,0)});
test('bank tax visual reports exactly 50 once',()=>{const g=newGame();g.players[0].cash=120;roll(g,'a',4);const takes=g.bankFx.filter(x=>x.direction==='take');assert.equal(takes.length,1);assert.equal(takes[0].amount,50);assert.equal(g.players[0].cash,70);assert.equal(g.debts.length,0)});
test('player-to-player rent emits an explicit transfer visual',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};g.turn=1;g.phase='roll';roll(g,'b',1);const fx=g.bankFx.find(x=>x.source==='player');assert.ok(fx);assert.equal(fx.from,'b');assert.equal(fx.to,'a');assert.equal(fx.amount,board.streets[0].rent*3)});
test('money effects carry natural reasons for rent and purchases',()=>{const g=newGame();g.owners[1]={id:'a',level:0,mortgaged:false};g.turn=1;g.phase='roll';roll(g,'b',1);const rentFx=g.bankFx.find(x=>x.source==='player');assert.match(rentFx.reason,/por el alquiler de la propiedad/i);const h=newGame();roll(h,'a',1);G.act(h,board,'a',{type:'buy'});const buyFx=h.bankFx.find(x=>x.to==='bank');assert.match(buyFx.reason,/por comprar la propiedad/i)});

test('GO card is shown before its movement is resolved',()=>{const g=newGame();g.players[0].pos=6;g.decks.chance=[2];roll(g,'a',1);assert.equal(g.players[0].pos,7);assert.equal(g.phase,'cardMove');assert.equal(g.event.kind,'card');assert.match(g.event.text,/GO/i);const firstMove=g.movement;assert.equal(firstMove.from,6);assert.equal(firstMove.to,7);G.act(g,board,'a',{type:'resolveCardMove'});assert.equal(g.players[0].pos,0);assert.equal(g.players[0].cash,1500);assert.equal(g.movement.source,'card')});
test('resolveCardMove cannot run before a staged card transfer exists',()=>{const g=newGame();assert.throws(()=>G.act(g,board,'a',{type:'resolveCardMove'}),/Acción desconocida|Espera|traslado/i)});

test('thematic sound events are emitted before their matching money visuals',()=>{const tax=newGame();roll(tax,'a',4);assert.equal(tax.soundEvents[0].sound,'tax');assert.ok(tax.soundEvents[0].id<tax.bankFx[0].id);const station=newGame();roll(station,'a',5);assert.equal(station.soundEvents[0].sound,'station');const build=newGame();build.owners[1]={id:'a',level:0,mortgaged:false};build.owners[3]={id:'a',level:0,mortgaged:false};G.act(build,board,'a',{type:'build',position:1});assert.equal(build.soundEvents[0].sound,'build');assert.ok(build.soundEvents[0].id<build.bankFx[0].id);const mortgage=newGame();mortgage.owners[1]={id:'a',level:0,mortgaged:false};G.act(mortgage,board,'a',{type:'mortgage',position:1});assert.equal(mortgage.soundEvents[0].sound,'mortgage');assert.ok(mortgage.soundEvents[0].id<mortgage.bankFx[0].id)});

test('GO, jail and cartillas carry sequencing metadata for their sounds',()=>{const go=newGame();go.players[0].pos=39;roll(go,'a',1);assert.equal(go.movement.passedGo,true);assert.equal(go.bankFx.find(x=>x.source==='go').amount,200);const jail=newGame();jail.players[0].pos=10;jail.players[0].jail=2;jail.players[0].cash=300;G.act(jail,board,'a',{type:'release',method:'pay'});assert.equal(jail.soundEvents[0].sound,'jail');assert.ok(jail.soundEvents[0].id<jail.bankFx[0].id);const card=newGame();card.players[0].pos=1;card.decks.community=[2];roll(card,'a',1);assert.equal(card.event.kind,'card');assert.equal(card.event.deck,'community');assert.equal(card.event.effect,'birthday')});
